/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Funcionario;

import Dados.AppDao;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author enzod
 */
public class ListarConsultoria extends javax.swing.JFrame {

    /**
     * Creates new form ListarConsultoria
     */
    public ListarConsultoria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblConsultoria = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        asdas = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtCnpj = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtMensagem = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        tblConsultoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CNPJ", "Mensagem"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblConsultoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblConsultoriaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblConsultoria);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 190, 550, 170);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(320, 40, 160, 110);

        asdas.setText("Cnpj: ");
        getContentPane().add(asdas);
        asdas.setBounds(60, 70, 60, 30);

        jScrollPane3.setViewportView(txtCnpj);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(110, 70, 110, 40);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Mensagem Selecionada: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(580, 110, 150, 30);

        txtMensagem.setColumns(20);
        txtMensagem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMensagem.setLineWrap(true);
        txtMensagem.setRows(5);
        txtMensagem.setWrapStyleWord(true);
        jScrollPane4.setViewportView(txtMensagem);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(580, 180, 340, 180);

        setSize(new java.awt.Dimension(957, 406));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {            
            String u = txtCnpj.getText();
            ResultSet usuario = new AppDao().carregarDadosConsultoria(u);
            DefaultTableModel tblModelo = (DefaultTableModel) tblConsultoria.getModel();
            //Nesse comando ele limpa a tebela
            tblModelo.setRowCount(0);
            
            //Percorrendo toda os usuários presentes no BD, para depois colocarmos num modelo e 
            while(usuario.next()){    
                if(!usuario.getString("mensagem").equals(" ")){
                        Object linha[] = {
                        usuario.getString("fk_cnpj"),
                        usuario.getString("mensagem")
                    };
                    tblModelo.addRow(linha);
                }else if(!u.equals("")){
                    JOptionPane.showMessageDialog(null, "Não possúi uma mensagem cadastrada");
                    break;
                }else{
                    continue;
                }
            }
        } catch (java.sql.SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: "+ex.getMessage());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ListarConsultoria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tblConsultoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblConsultoriaMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblConsultoria.getModel();
        int row = tblConsultoria.getSelectedRow();
        
        txtMensagem.setText(model.getValueAt(row, 1).toString());
    }//GEN-LAST:event_tblConsultoriaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarConsultoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarConsultoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarConsultoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarConsultoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarConsultoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel asdas;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblConsultoria;
    private javax.swing.JTextPane txtCnpj;
    private javax.swing.JTextArea txtMensagem;
    // End of variables declaration//GEN-END:variables
}
