/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cliente;
import Adm.*;
import Funcionario.*;
import Geral.*;
/**
 *
 * @author enzod
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }
    
    public Menu(String cargo) {
        initComponents();
        if(cargo.equalsIgnoreCase("ADM")){
            mnuConfig.setVisible(false);
            mnuConsultoria.setVisible(false);
            mnuPublicacoes.setVisible(false);
            itmContato.setVisible(false);
        }else if(cargo.equalsIgnoreCase("Funcionário")){
            mnuConfig.setVisible(false);
            mnuConsultoria.setVisible(false);
            mnuPublicacoes.setVisible(false);
            itmInativarFuncionario1.setVisible(false);
            itmCadastrarFuncionario.setVisible(false);
        }else if(cargo.equalsIgnoreCase("Cliente")){
            mnuBuscar.setVisible(false);
            mnuCadastrar.setVisible(false);
            mnuAlterarInfo.setVisible(false);
        }else{
        
        }
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuConfig = new javax.swing.JMenu();
        itmAlterar = new javax.swing.JMenuItem();
        mnuExcluir = new javax.swing.JMenuItem();
        mnuConsultoria = new javax.swing.JMenu();
        mnuAgendar = new javax.swing.JMenuItem();
        mnuPublicacoes = new javax.swing.JMenu();
        mnuEscrever = new javax.swing.JMenuItem();
        mnuStatus = new javax.swing.JMenuItem();
        mnuAlterarInfo = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        itmAlterarCliente1 = new javax.swing.JMenuItem();
        itmInativarCliente1 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        itmAlterarFuncionario1 = new javax.swing.JMenuItem();
        itmInativarFuncionario1 = new javax.swing.JMenuItem();
        mnuCadastrar = new javax.swing.JMenu();
        itmCadastrarCliente = new javax.swing.JMenuItem();
        itmCadastrarFuncionario = new javax.swing.JMenuItem();
        mnuBuscar = new javax.swing.JMenu();
        itmListarClientes = new javax.swing.JMenuItem();
        itmListarConsultoria = new javax.swing.JMenuItem();
        itmListarFuncionarios = new javax.swing.JMenuItem();
        itmListarStatus = new javax.swing.JMenuItem();
        mnuAjuda = new javax.swing.JMenu();
        itmContato = new javax.swing.JMenuItem();
        mnuDocumentacao = new javax.swing.JMenu();
        itmManualUsuario = new javax.swing.JMenuItem();
        itmCodigoConsumidor = new javax.swing.JMenuItem();
        itmSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        mnuConfig.setText("Configurações");

        itmAlterar.setText("Alterar Informações");
        itmAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAlterarActionPerformed(evt);
            }
        });
        mnuConfig.add(itmAlterar);

        mnuExcluir.setText("Excluir Conta");
        mnuExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExcluirActionPerformed(evt);
            }
        });
        mnuConfig.add(mnuExcluir);

        jMenuBar1.add(mnuConfig);

        mnuConsultoria.setText("Consultoria");

        mnuAgendar.setText("Agendar");
        mnuAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAgendarActionPerformed(evt);
            }
        });
        mnuConsultoria.add(mnuAgendar);

        jMenuBar1.add(mnuConsultoria);

        mnuPublicacoes.setText("Publicações");

        mnuEscrever.setText("Escrever");
        mnuEscrever.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEscreverActionPerformed(evt);
            }
        });
        mnuPublicacoes.add(mnuEscrever);

        mnuStatus.setText("Status atual");
        mnuStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuStatusActionPerformed(evt);
            }
        });
        mnuPublicacoes.add(mnuStatus);

        jMenuBar1.add(mnuPublicacoes);

        mnuAlterarInfo.setText("Alterar info");

        jMenu8.setText("Cliente");

        itmAlterarCliente1.setText("Alterar");
        itmAlterarCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAlterarCliente1ActionPerformed(evt);
            }
        });
        jMenu8.add(itmAlterarCliente1);

        itmInativarCliente1.setText("Inativar");
        itmInativarCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmInativarCliente1ActionPerformed(evt);
            }
        });
        jMenu8.add(itmInativarCliente1);

        mnuAlterarInfo.add(jMenu8);

        jMenu9.setText("Funcionario");

        itmAlterarFuncionario1.setText("Alterar ");
        itmAlterarFuncionario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAlterarFuncionario1ActionPerformed(evt);
            }
        });
        jMenu9.add(itmAlterarFuncionario1);

        itmInativarFuncionario1.setText("Inativar");
        itmInativarFuncionario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmInativarFuncionario1ActionPerformed(evt);
            }
        });
        jMenu9.add(itmInativarFuncionario1);

        mnuAlterarInfo.add(jMenu9);

        jMenuBar1.add(mnuAlterarInfo);

        mnuCadastrar.setText("Cadastrar");

        itmCadastrarCliente.setText("Cliente");
        itmCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadastrarClienteActionPerformed(evt);
            }
        });
        mnuCadastrar.add(itmCadastrarCliente);

        itmCadastrarFuncionario.setText("Funcionário");
        itmCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadastrarFuncionarioActionPerformed(evt);
            }
        });
        mnuCadastrar.add(itmCadastrarFuncionario);

        jMenuBar1.add(mnuCadastrar);

        mnuBuscar.setText("Buscar");

        itmListarClientes.setText("Clientes");
        itmListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListarClientesActionPerformed(evt);
            }
        });
        mnuBuscar.add(itmListarClientes);

        itmListarConsultoria.setText("Consultorias");
        itmListarConsultoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListarConsultoriaActionPerformed(evt);
            }
        });
        mnuBuscar.add(itmListarConsultoria);

        itmListarFuncionarios.setText("Funcionários");
        itmListarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListarFuncionariosActionPerformed(evt);
            }
        });
        mnuBuscar.add(itmListarFuncionarios);

        itmListarStatus.setText("Status Publicações");
        itmListarStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListarStatusActionPerformed(evt);
            }
        });
        mnuBuscar.add(itmListarStatus);

        jMenuBar1.add(mnuBuscar);

        mnuAjuda.setText("Ajuda");
        mnuAjuda.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N

        itmContato.setText("Contato");
        itmContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmContatoActionPerformed(evt);
            }
        });
        mnuAjuda.add(itmContato);

        mnuDocumentacao.setText("Documentação");
        mnuDocumentacao.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N

        itmManualUsuario.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        itmManualUsuario.setText("Manual do usuário");
        mnuDocumentacao.add(itmManualUsuario);

        itmCodigoConsumidor.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        itmCodigoConsumidor.setText("Código do consumidor");
        itmCodigoConsumidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCodigoConsumidorActionPerformed(evt);
            }
        });
        mnuDocumentacao.add(itmCodigoConsumidor);

        itmSobre.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        itmSobre.setText("Sobre");
        mnuDocumentacao.add(itmSobre);

        mnuAjuda.add(mnuDocumentacao);

        jMenuBar1.add(mnuAjuda);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(560, 337));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAgendarActionPerformed
        new AgendarConsultoria().setVisible(true);
    }//GEN-LAST:event_mnuAgendarActionPerformed

    private void mnuEscreverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEscreverActionPerformed
        new CriarPublicacao().setVisible(true);
    }//GEN-LAST:event_mnuEscreverActionPerformed

    private void mnuStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuStatusActionPerformed
        new ListarStatus().setVisible(true);
    }//GEN-LAST:event_mnuStatusActionPerformed

    private void itmCodigoConsumidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCodigoConsumidorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmCodigoConsumidorActionPerformed

    private void itmCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadastrarClienteActionPerformed
        new CadastrarCliente().setVisible(true);
    }//GEN-LAST:event_itmCadastrarClienteActionPerformed

    private void itmCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadastrarFuncionarioActionPerformed
        new CadastrarFuncionario().setVisible(true);
    }//GEN-LAST:event_itmCadastrarFuncionarioActionPerformed

    private void itmListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListarClientesActionPerformed
        new ListarCliente().setVisible(true);
    }//GEN-LAST:event_itmListarClientesActionPerformed

    private void itmListarConsultoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListarConsultoriaActionPerformed
        new ListarConsultoria().setVisible(true);
    }//GEN-LAST:event_itmListarConsultoriaActionPerformed

    private void itmListarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListarFuncionariosActionPerformed
        new ListarFuncionario().setVisible(true);
    }//GEN-LAST:event_itmListarFuncionariosActionPerformed

    private void itmListarStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListarStatusActionPerformed
        new ListarStatus().setVisible(true);
    }//GEN-LAST:event_itmListarStatusActionPerformed

    private void itmAlterarFuncionario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAlterarFuncionario1ActionPerformed
        new AlterarInfoFuncionario().setVisible(true);
    }//GEN-LAST:event_itmAlterarFuncionario1ActionPerformed

    private void itmInativarFuncionario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmInativarFuncionario1ActionPerformed
        new admExcluirFuncionario().setVisible(true);
    }//GEN-LAST:event_itmInativarFuncionario1ActionPerformed

    private void itmAlterarCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAlterarCliente1ActionPerformed
        new AlterarInfoCliente().setVisible(true);
    }//GEN-LAST:event_itmAlterarCliente1ActionPerformed

    private void itmAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAlterarActionPerformed
        new AlterarInfoCliente().setVisible(true);
    }//GEN-LAST:event_itmAlterarActionPerformed

    private void mnuExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExcluirActionPerformed
        new ExcluirCliente().setVisible(true);
    }//GEN-LAST:event_mnuExcluirActionPerformed

    private void itmInativarCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmInativarCliente1ActionPerformed
        new AdmExcluirCliente().setVisible(true);
    }//GEN-LAST:event_itmInativarCliente1ActionPerformed

    private void itmContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmContatoActionPerformed
        new Cliente.alo.primeiro().setVisible(true);
    }//GEN-LAST:event_itmContatoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmAlterar;
    private javax.swing.JMenuItem itmAlterarCliente1;
    private javax.swing.JMenuItem itmAlterarFuncionario1;
    private javax.swing.JMenuItem itmCadastrarCliente;
    private javax.swing.JMenuItem itmCadastrarFuncionario;
    private javax.swing.JMenuItem itmCodigoConsumidor;
    private javax.swing.JMenuItem itmContato;
    private javax.swing.JMenuItem itmInativarCliente1;
    private javax.swing.JMenuItem itmInativarFuncionario1;
    private javax.swing.JMenuItem itmListarClientes;
    private javax.swing.JMenuItem itmListarConsultoria;
    private javax.swing.JMenuItem itmListarFuncionarios;
    private javax.swing.JMenuItem itmListarStatus;
    private javax.swing.JMenuItem itmManualUsuario;
    private javax.swing.JMenuItem itmSobre;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuAgendar;
    private javax.swing.JMenu mnuAjuda;
    private javax.swing.JMenu mnuAlterarInfo;
    private javax.swing.JMenu mnuBuscar;
    private javax.swing.JMenu mnuCadastrar;
    private javax.swing.JMenu mnuConfig;
    private javax.swing.JMenu mnuConsultoria;
    private javax.swing.JMenu mnuDocumentacao;
    private javax.swing.JMenuItem mnuEscrever;
    private javax.swing.JMenuItem mnuExcluir;
    private javax.swing.JMenu mnuPublicacoes;
    private javax.swing.JMenuItem mnuStatus;
    // End of variables declaration//GEN-END:variables
}
